services:
  app:
    build: .
    container_name: twbc-site
    restart: unless-stopped
    # ports:
    #   - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - twbc-site

networks:
  twbc-site:
    driver: bridge
