services:
  app:
    build: .
    container_name: twbc-site
    restart: unless-stopped
    # ports:
    #   - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - twbc-site
    volumes:
      - twbc-site:/app

networks:
  twbc-site:
    driver: bridge

volumes:
  twbc-site:
    name: twbc-site
